###
GET http://localhost:5173/api/testQuestion

###

GET http://localhost:5173/api/testQuestions2

###

GET http://localhost:5173/api/users

###

GET http://localhost:5173/api/testResults/1

###

DELETE http://localhost:3000/api/deleteUser/5

DELETE http://localhost:3000/api/user/5
